[package]
name = "tests"
version = "0.26.0"
edition = "2021"

[dependencies]
bollard = "0.10"
tokio = {version = "1.16.1", features = ["rt", "macros", "process"]}
tokio-stream = "0.1"
port_check = "0.1.5"
anyhow = "1.0.57"
lazy_static = "1.4.0"
async-stream = "0.3.3"
